# Calculadoras Científicas

Fazer as contas na mão é coisa do passado, com o advento dos computadores não faz sentido mandar o aluno ficar horas e horas fazendo contas de somar e multiplicar. Acredito ser muito mais proveitoso ensinar a vocês conceitos estatísticos e aplicação e, por isso, esse curso será todo desenvolvido utilizando calculadoras científicas. Na verdade verdadeira, por mim o curso nem seria mais dado com calculadoras e, sim, direto no computador em R. Um sonho distânte mas um dia chego lá.

Enquanto esse dia não chega, vamos ao que interessa e aprender alguns truques na calculadora antes de começar a com a estatística de fato.

## Modelos

As melhores calculadoras científicas, até o momento, são a da marca CASIO. O modelo mais comum é a fx-82MS e você pode adquirir em qualquer loja de eletrônicos. A CASIO também tem um outro modelo que é a fx-82ES PLUS, este modelo é menos comum, mas também faz tudo que precisamos aqui pro curso. Qualquer outra calculadora científica de outra marca vai seguir os mesmos padrões ou da fx-82MS (a grande maioria) ou da fx-82ES PLUS.
Não se preocupe, apenas identifique na sua calculadora qual tipo de modelo da CASIO ela segue. 

Outras marcas disponíveis com o preço mais acessível são a Kenko e NWAY. Caso você opte por estas marcas certifique-se que ela tenha setas direcionais (cima, baixo, esquerda e direita). Isto será indispensável para a gente no curso e não será possível acompanhar o assunto em calculadoras sem setas, ok?

## Teclas básicas

Essas teclas são logo as primeiras instruções que vamos aprender e servirá para qualquer modelo que você venha a utlizar. Lembre-se que nossas calculadoras estão em inglês, mas não se preocupe que não é muita coisa. 

Para ligar sua calculadora é fácil, apenas aperte a tecla **ON** no canto superior direito. Para desligar você precisa apertar em **OFF**, que está logo em cima da tecla **AC**. Para acessar esses comandos que estão loga acima das teclas você precisa apertar antes a tecla **SHIFT** que está no canto superior esquerdo. Não é necessário apertar e segurar o **SHIFT** como no seu computador, apenas aperte uma vez (perceba que na tela, no canto superior esquerdo, irá aparecer um `S`) e depois aperte **AC**, isto desligará sua calculadora.

Diferentes das calculadoras normais, a científica precisa que você aperte **=** para que uma operação seja exibida na tela. Exemplo, digite na sua calculadora $2 + 2$, perceba que a operação aparece em cima da tela, mas embaixo continua $0$. Para que qualquer operação seja concluída você precisa apertar a tecla **=**.

Muitas vezes digitamos algo errado, é normal. Caso precise apagar algo use **DEL** para a última coisa que você digitou ou apague tudo usando **AC**.

## Armazenando os dados

No canto superior direito você irá encontrar a teclas **MODE**, esta é a tecla principal da nossa calculadora e é aqui que acontece a mágica de não precisar fazer as contas na mão. Aqui aparecerão algumas diferenças entre as calculadoras, mas não se preocupe, será mostrado como se faz nas duas ;)

### fx-82MS

A primeira coisa a se fazer é apertar tecla **MODE**, ao fazer isto irão aparecer três opções: **COMP**, **SD** e **REG**. A opção 1 (**COMP**) é a própria calculadora, volte para este modo quando terminar suas contas. A opção 3 (**REG**) é o modo regressão e será visto mais na frente. A opção que queremos aqui é a de número 2 (**SD**) e eu chamo ela de modo estatísica. 

Como está na opção 2, basta apenas apertar a tecla **2** da sua calculadora. Perceba que na tela da sua calculadora agora aparece la em cima SD. Pronto, estamos no modo estatística!

Em cima da tecla **AC** tem a tecla **M+**, perceba que logo abaixo desta tecla tem escrito `DT[CL]`^[Lembre-se que as calculadoras estão em inglês. DT significa *Data* (Dados) e CL significa *Clear* (apagar).]. Esta tecla no modo estatística servirá para adicionar e remover números.

Suponha a sequência abaixo, vamos por estes números na calculadora!

$$ 3,\space 4,\space 4,\space 4,\space 6,\space 7,\space 7 $$
É simples, basta apertar a tecla **3** e depois **M+**. Aparecerá na sua tela `n = 1`, isto quer dizer que só um número esta armazenado. Aperte para baixo no direcional e aparecerá `x1 = 3` que significa que o primeiro número que você inseriu foi 3. Se você apertar novamente o direcional para baixo irá aparecer na tela `freq1 = 1`, isto significa que o número só se repetiu uma vez, ou seja, possui freqência 1.  

Imagine, agora, que você digitou errado, por exemplo, 2 ao invès de 3. Na sua tela iria aparecer `x1 = 2`, para corrigir este erro basta digitar o número correto (no nosso caso 3) e apertar a tecla **=**. 

O próximo número é o 4, mas ele se repete três vezes. Você poderia até pôr ele três vezes usando **4** e depois **M+**, contudo, é mais fácil e rápido pôr ele uma vez única vez e depois corrigir a frequência. Adicione o 4 utilizando **4** e depois **M+**, depois disso use o direcional até encontrar o 4 (caso não tenha errado nada até agora, aparecerá na tela `x2 = 4`. Perceba que `x2` é por que o segundo número que colocamos foi 4, o primeiro foi um 3, lembra?). Agora que você encontrou o valor que deseja alterar a frequência, aperte mais uma vez o direcional para baixo e irá aparecer na tela `freq2 = 1`. Como ele apareceu três vezes, apenas aperte **3** e **M+**, pronto agora o 4 três frequência 3 :)

Agora você já sabe pôr os números e ajustar as repetições. E se você quiser apagar? Caso queira remover um número, você irá utilizar mesma tecla **M+**, mas precisará incluir o **SHIFT**. Por exemplo, caso queira apagar o 3, vá com o direcional até este número e quando aparecer na tela `x1 = 3` aperte **SHIFT** e depois **M+**. Perceba que este procedimento remove aquele número da sequência, ou seja, se você apagasse o 4 com frequência 3, todos os três números 4 seriam apagados.

Por fim, para apagar todos os números e voltar ao início, basta alterar o modo da calucludara. Simples, aperte **MODE** e depois **1** para voltar para a calculadora normal, ou **MODE** e depois  **2** se quiser voltar para o modo estatística.

### fx-82ES PLUS

Nesta calculadora é mais simples inserir os números, mas ela precisa de umas configurações antes. 
Aperte **SHIFT** e depois **MODE**, esta é a tela de *setup*. Aperte para baixo no direcional e escolha a opção 3 (`STAT`). Na tela vai aparecer `Frequency?`, aperte a opção 1 (ON).

Novamente, suponha a sequência abaixo, vamos por estes números na calculadora!

$$ 3,\space 4,\space 4,\space 4,\space 6,\space 7,\space 7 $$

Aperte a tecla **MODE**, em seguida **2** (`STAT`) e por último **1** (`1 - VAR`). Se você fez o *setup* corretamente irão aparecer duas colunas: X e FREQ. A primeira coluna (X) será onde você irá digitar os números da sequência e segunda coluna (FREQ) será representará a quantidade de repetições daquele número, ou seja, a frequência. Vamos inserir o primeiro número da sequência, aperte a tecla **3** e depois **=**. Perceba que na coluna de frequência apareceu o valor 1, ou seja, o 3 só se repete uma vez. 

Suponha que você digitou errado, por exemplo, 2 ao invès de 3. Para corrigir é simples, use o direcional até o número que você digitou e o corrija, no nosso caso, vá até o 2 e tecle **3** e depois **=**. 

Para colocar o próximo número o procedimento é o mesmo, aperte **4** e depois **=**. Perceba que a frequência do 4 também apareceu 1 na calculadora, mas na nossa sequência ele aparece 3 vezes. Para corrigir isto, use o direcional até chegar na segunda linha da coluna de frequência (ao lado do 4) e aperte **3** e depois **=**. 

Por fim, para apagar todos os números, basta apertar **MODE** e depois **1** (`COMP`).
