---
title: "Distribuição de Frequência"
author: "Kevyn Gonçalves dos Santos"
date: "26/11/2019"
output: html_document
---

# Distribuição de frequência

  A distribuição de frequência é um agrupamento de dados distribuídos em classes, frequências e frequências acumuladas. Esses dados podem ser representados em tabelas ou gráficos, chamados de histogramas.

**Classes**: são os principais dados da tabela. Possuem intervalos entre o número inferior e o número superior, onde o superior não pertence ao intervalo. Para acharmos o ponto médio, tiramos a média entre a soma dos intervalos de cada classe.

**Frequências**: São as ocorrências dos valores dos intervalos de cada classe.

**Frequência Acumulada**: É a soma de todas as classes anteriores até a ultima classe.

$\color{green}{\text{(Exemplo 1)}}$: De acordo com os passos, descubra a média, mediana, o desvio de padrão e a assimetria.

**Classe** |**Frequência**|**F.Acumulada**|
-----------|--------------|---------------|
**60-70**  |    16        |     16        |
**70-80**  |     4        |     20        |
**80-90**  |     2        |     22        |
**90-100** |     8        |     30        |
**100-110**|     6        |     36        |
**110-120**|    14        |     50        |
**120-130**|    10        |     60        |
**130-140**|    12        |     72        |


**Passo 1**: descobrir os pontos médios e adicionar à calculadora no modo SD (Ex:65;75;85;95;105;115;125;135) editando suas respectivas frequências.

**Passo 2**: Descobrir a média    **$\overline x$ = 102.5**

**Passo 3**: Descobrir a mediana (a posição da média das frequências dividida pela frequência multiplicado pelo tamanho da classe somado ao inicio dela)  **$\tilde{x}$=105**

**Passo 4**: Descobrir o desvio de padrão  **σ=25.42**

**Passo 5**: Descobrir a assimetria  **A= -0.2**

**Passo 6**: Desenhar o $\color{yellow}{\text{Histograma}}$




$\color{green}{\text{(Exemplo 2)}}$:Seguindo os mesmos passos anteriores.Descubra a média, mediana, o desvio de padrão e a assimetria.Descobrindo também o 1º e 3º quartil, o 1º e 9º decil e a curtose.


**Classe** |**Frequência**|**F.Acumulada**|
-----------|--------------|---------------|   
**15-25**  |     5        |     5         |   
**25-35**  |    10        |     15        |     
**35-45**  |    15        |     30        |
**45-55**  |    10        |     40        |
**55-65**  |     5        |     45        |
**65-75**  |    14        |     59        |
**75-85**  |     0        |     59        |
**85-95**  |     1        |     60        |


$\overline x$=47.83…
$\tilde{x}$=55
σ=17.03…
Q1=25   ,Q3=55
D1=26   ,D9=71.42
A=-1.26
K=0.3

**OBS**: Antes de calcular a curtose, deverá descobrir a posição dos quartis e decis.(a posição do quantil, dividida pela frequência multiplicadapelo tamanho da classe somado ao inicio dela).

***

## Exercícios

1.Qual gráfico é o mais adequado para se fazer a representaçao gráfica de uma distribuição de frequências?

a) Diagrama de Barras

b) Pictograma

c) Polígono de Frenquência

d) Histograma

2.Em 20 dias um professor anotou o número de alunos ausentes, e fez a tabela de frequências abaixo:

 Aulos Ausentes | Frequências | Percentual |
----------------|-------------|------------|
 0-3            |      5      |     A      |
 4-7            |    **B**    |     25     |
 8-12           |      C      |     D      |
 12-16          |      2      |     E      |
 
 Qual o número que a letra **B** corresponde?
 
    A) 5
    
    B) 6
    
    C) 7
    
    D) 8
    
    E) 9

3.A tabela abaixo indica a frequência relativa de 4 produtos (A,B,C,D) encontrados em 30 lojas.

 Produtos |  Frenquência Absoluta |
----------|-----------------------|
 A        |           0,3         |
 B        |           0,4         |
 C        |           0,2         |
 D        |           0,1         |
 
 O número de lojas que os produtos **B** ou **D** foram encontrados foi de?
   
  A)  7
  
  B)  9
  
  C)  12
  
  D)  15
  
  E)  18
  
4.Foi realizada uma pesquisa para se saber qual o número de Tv’s em cada casa, 200 residências participaram da pesquisa. 

  N°de TV's | Frequência Absoluta |
------------|---------------------|
  0         |           8         |   
  1         |         118         |
  2         |          48         |  
  3         |          21         |
  4         |           5         |
  
 Qual a porcentagem de casas que têm mais de uma TV?
 
  A)	12%
  
  B)	37%
  
  C)	63%
  
  D)	46%
  
  E)	74%

5.O máximo de um gráfico de frequência absoluta acumulada de uma variável discreta é?

  A)	Decil
  
  B)	Amplitude
  
  C)	Moda
  
  D)	Cumulativo
  
  E)	Número total de observações

6.Polígonos de frequência e Histogramas são representacões gráficas de distribuições:

  A)	não uniformes
  
  B)	de acumulações
  
  C)	uniformes
  
  D)	assimétricas
  
  E)	de Frequências

7.A tabela a seguir mostra uma entrevista feita com 50 clientes e está dividida por faixa etária.

 Ordem de faixa etária | Faixa etária | Número de Clientes |
-----------------------|--------------|--------------------|
         1°            |  18-25       |        12          | 
         2°            |  25-32       |        24          |
         3°            |  32-40       |         8          |
         4°            |  40-48       |         6          |
         
 É correto afirmar que:
 
  A)	Pelo menos 1 , na terceira faixa etária, têm 32 anos.
  
  B)	Há, na primeira faixa etária, ao menos 1 têm 25 anos.
  
  C)	12%  tem mais 18 anos.
  
  D)	48% tem entre 18 e 32 anos.
  
  E)	88% têm menos de 40 anos.

8.Considere a tabela a seguir

 Classes  | Frequências Acumuladas(%) |
----------|---------------------------|
 400-500  |            5              |
 500-600  |           10              | 
 600-700  |           20              |
 700-800  |           40              |
 800-900  |           55              |
 900-1000 |          100              |

 A estimativa da distribuição que não é superada em 60% das observações é?
 
  A)	890.88
  
  B)	911.11
  
  C)	890,66
  
  D)	915,67
  
  E)	987,98

9.Dos 110 empregados de uma empresa, 80 são casados, 70 possuem casa própria e 30 são solteiros e possuem casa própria. julgue o item a seguir.

 Dos empregados que possuem casa própria há mais solteiros que casados.
 
  A)	Certo
  
  B)	Errado
  
10.Foram entrevistados 800 telespectadores sobre o programa de televisão de sua preferência e se obteve a seguinte tabela:

 Programas de TV | Número de Telespectadores |
 ----------------|---------------------------|
 Novelas         |           300             |
 Esportes        |           128             |
 Filmes          |            80             |
 Noticiários     |            32             |
 Shows           |           200             |
 
 
 
 Construa um quadro com a distibuição de frequência relativa.
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 ***
 






